import { app, BrowserWindow, dialog, ipcMain, session, Menu, type Cookie } from "electron";
import path from "node:path";
import fs from "node:fs";
import type { Platform } from "@vbd/shared";

const isDev = !app.isPackaged;
let mainWindow: BrowserWindow | null = null;

/* ------------------------------- resources -------------------------------- */

function binDir(): string {
  return isDev ? path.join(process.cwd(), "bin") : path.join(process.resourcesPath, "bin");
}
function webDir(): string {
  return isDev
    ? path.join(process.cwd(), "apps", "web", "out")
    : path.join(process.resourcesPath, "web");
}

/* --------------------------------- cookies -------------------------------- */

const LOGIN_URLS: Record<Platform, string> = {
  bilibili: "https://passport.bilibili.com/login",
  tiktok: "https://www.tiktok.com/login",
  douyin: "https://www.douyin.com/",
  youtube: "https://accounts.google.com/ServiceLogin?continue=https%3A%2F%2Fwww.youtube.com%2F",
  unknown: "https://www.google.com/",
};
const COOKIE_DOMAINS: Record<Platform, string[]> = {
  bilibili: [".bilibili.com"],
  tiktok: [".tiktok.com"],
  douyin: [".douyin.com"],
  youtube: [".youtube.com", ".google.com"],
  unknown: [],
};

/**
 * Cookie names that only exist on a *logged-in* session. We capture all
 * matching-domain cookies (anonymous ones still help anti-bot), but only report
 * `loggedIn: true` — and show the ✓ — when one of these is present. Otherwise the
 * tick was a false positive (Douyin sets ttwid/__ac_nonce for guests too).
 */
const SESSION_COOKIES: Record<Platform, string[]> = {
  bilibili: ["SESSDATA"],
  tiktok: ["sessionid", "sid_tt"],
  douyin: ["sessionid", "sessionid_ss"],
  youtube: ["SID", "__Secure-3PSID", "__Secure-1PSID"],
  unknown: [],
};

export interface LoginResult {
  /** Path to the captured cookies.txt, or null if nothing matched. */
  path: string | null;
  /** True only when a real logged-in session cookie was captured. */
  loggedIn: boolean;
}

function toNetscape(cookies: Cookie[]): string {
  const lines = ["# Netscape HTTP Cookie File", "# Generated by VideoBulkDownloader"];
  for (const c of cookies) {
    const includeSub = c.domain?.startsWith(".") ? "TRUE" : "FALSE";
    const secure = c.secure ? "TRUE" : "FALSE";
    const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0;
    lines.push(
      [c.domain, includeSub, c.path || "/", secure, String(expiry), c.name, c.value].join("\t"),
    );
  }
  return lines.join("\n") + "\n";
}

/** Open a login window; when the user closes it, capture that platform's cookies. */
function loginAndCaptureCookies(platform: Platform): Promise<LoginResult> {
  return new Promise((resolve) => {
    const win = new BrowserWindow({
      width: 1024,
      height: 800,
      title: `Sign in to ${platform} — log in, then close this window`,
      autoHideMenuBar: true,
      webPreferences: { partition: undefined }, // default persistent session
    });
    win.loadURL(LOGIN_URLS[platform]).catch(() => {});
    win.on("closed", async () => {
      try {
        const ses = session.defaultSession;
        const bases = COOKIE_DOMAINS[platform].map((d) => d.replace(/^\./, ""));
        // Grab ALL cookies and keep any whose domain matches — more robust than an
        // exact domain filter (covers passport./api./www. subdomains, httpOnly, etc.).
        const all = await ses.cookies.get({});
        const matched = all.filter((c) => bases.some((b) => (c.domain ?? "").includes(b)));
        if (matched.length === 0) return resolve({ path: null, loggedIn: false });
        const file = path.join(app.getPath("userData"), `cookies-${platform}.txt`);
        fs.writeFileSync(file, toNetscape(matched), "utf8");
        const sessionNames = SESSION_COOKIES[platform];
        const loggedIn = matched.some((c) => sessionNames.includes(c.name));
        resolve({ path: file, loggedIn });
      } catch {
        resolve({ path: null, loggedIn: false });
      }
    });
  });
}

/* --------------------------------- window --------------------------------- */

function createWindow(port: number): void {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 860,
    backgroundColor: "#0b0e14",
    autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, "preload.cjs"),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });
  Menu.setApplicationMenu(null);
  mainWindow.loadURL(`http://127.0.0.1:${port}/`);
  mainWindow.on("closed", () => {
    mainWindow = null;
  });
}

/* ---------------------------------- boot ---------------------------------- */

async function boot(): Promise<void> {
  // Env must be set BEFORE the server module loads (config.ts reads it at init),
  // so the server is imported dynamically below.
  process.env.VBD_BIN_DIR = binDir();
  process.env.VBD_DATA_DIR = app.getPath("userData");
  process.env.VBD_WEB_DIR = webDir();
  process.env.VBD_PORT = process.env.VBD_PORT ?? "4319";
  process.env.LOG_LEVEL = process.env.LOG_LEVEL ?? "warn";

  const server = await import("@vbd/server");
  await server.startServer();

  ipcMain.handle("pick-folder", async (_e, initialDir?: string) => {
    const res = await dialog.showOpenDialog(mainWindow ?? undefined!, {
      properties: ["openDirectory", "createDirectory"],
      defaultPath: initialDir || undefined,
    });
    return res.canceled || !res.filePaths[0] ? null : res.filePaths[0];
  });
  ipcMain.handle("login", (_e, platform: Platform) => loginAndCaptureCookies(platform));

  createWindow(server.PORT);
}

app.whenReady().then(boot).catch((err) => {
  console.error("Failed to start:", err);
  dialog.showErrorBox("VideoBulkDownloader failed to start", String(err?.stack ?? err));
  app.quit();
});

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0 && mainWindow === null) {
    // Re-create on macOS dock activate; port already bound.
    createWindow(Number(process.env.VBD_PORT ?? 4319));
  }
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});
